create table if not exists farmer_credentials (
 farmer_id bigint primary key references farmers(id) on delete cascade,
 password_hash text not null,
 password_updated_at timestamptz not null default now(),
 last_login_at timestamptz,
 created_at timestamptz not null default now()
);
create table if not exists farmer_sessions (
 id bigint generated by default as identity primary key,
 farmer_id bigint not null references farmers(id) on delete cascade,
 token_hash text not null unique,
 created_at timestamptz not null default now(), expires_at timestamptz not null, user_agent text
);
create index if not exists idx_farmer_sessions_farmer on farmer_sessions(farmer_id);
alter table farmers enable row level security;
alter table crops enable row level security;
alter table mandis enable row level security;
alter table mandi_crop_acceptance enable row level security;
alter table prices enable row level security;
alter table bookings enable row level security;
alter table queue_tokens enable row level security;
alter table payments enable row level security;
alter table notifications enable row level security;
alter table farmer_credentials enable row level security;
alter table farmer_sessions enable row level security;
