-- Kisan Queue baseline schema. Safe for a fresh Supabase project.
create table if not exists farmers (
 id bigint generated by default as identity primary key,
 full_name text not null,
 mobile text not null unique,
 farmer_id text unique,
 village text, district text, state text, preferred_language text not null default 'hi',
 created_at timestamptz not null default now()
);
create table if not exists crops (
 id bigint generated by default as identity primary key,
 name text not null unique,
 unit text not null default 'quintals',
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists mandis (
 id bigint generated by default as identity primary key,
 name text not null,
 address text, district text, state text, latitude double precision, longitude double precision,
 operating_hours text not null default '08:00-18:00',
 contact text, status text not null default 'ACTIVE' check(status in ('ACTIVE','INACTIVE')),
 capacity_per_slot integer not null default 10,
 created_at timestamptz not null default now()
);
create table if not exists mandi_crop_acceptance (
 mandi_id bigint not null references mandis(id) on delete cascade,
 crop_id bigint not null references crops(id) on delete cascade,
 accepted boolean not null default true,
 primary key(mandi_id,crop_id)
);
create table if not exists prices (
 id bigint generated by default as identity primary key,
 mandi_id bigint references mandis(id) on delete cascade,
 crop_id bigint not null references crops(id) on delete cascade,
 price_per_quintal numeric(12,2), effective_date date not null,
 source text, created_at timestamptz not null default now()
);
create table if not exists bookings (
 id bigint generated by default as identity primary key,
 farmer_id bigint not null references farmers(id) on delete cascade,
 mandi_id bigint not null references mandis(id),
 crop_id bigint not null references crops(id),
 quantity_quintals numeric(12,2) not null check(quantity_quintals>0 and quantity_quintals<=10000),
 booking_date date not null,
 slot_start time not null,
 slot_end time not null,
 status text not null default 'BOOKED' check(status in ('BOOKED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW')),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists queue_tokens (
 id bigint generated by default as identity primary key,
 booking_id bigint not null unique references bookings(id) on delete cascade,
 token_number bigint not null unique,
 counter_id text,
 status text not null default 'WAITING' check(status in ('WAITING','CALLED','SERVING','HOLD','COMPLETED','CANCELLED','SKIPPED')),
 created_at timestamptz not null default now(), called_at timestamptz, completed_at timestamptz
);
create table if not exists payments (
 id bigint generated by default as identity primary key,
 booking_id bigint not null references bookings(id) on delete cascade,
 farmer_id bigint not null references farmers(id) on delete cascade,
 amount numeric(14,2), status text not null default 'PENDING' check(status in ('PENDING','PROCESSING','PAID','FAILED')),
 reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists notifications (
 id bigint generated by default as identity primary key,
 farmer_id bigint not null references farmers(id) on delete cascade,
 type text not null,
 title text not null,
 message text not null,
 read_at timestamptz,
 created_at timestamptz not null default now()
);
create index if not exists idx_bookings_mandi_date on bookings(mandi_id,booking_date);
create index if not exists idx_bookings_farmer on bookings(farmer_id,created_at desc);
create index if not exists idx_tokens_status on queue_tokens(status);
create index if not exists idx_notifications_farmer on notifications(farmer_id,created_at desc);
create or replace function set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end $$;
drop trigger if exists bookings_updated_at on bookings;
create trigger bookings_updated_at before update on bookings for each row execute function set_updated_at();
drop trigger if exists payments_updated_at on payments;
create trigger payments_updated_at before update on payments for each row execute function set_updated_at();
