create table if not exists staff (
 id bigint generated by default as identity primary key,
 staff_code text not null unique,
 name text not null,
 role text not null check(role in ('operator','supervisor','admin')),
 mandi_id bigint references mandis(id) on delete set null,
 active boolean not null default true,
 created_at timestamptz not null default now()
);
create table if not exists staff_credentials (
 staff_id bigint primary key references staff(id) on delete cascade,
 password_hash text not null,
 password_updated_at timestamptz not null default now(),
 last_login_at timestamptz,
 created_at timestamptz not null default now()
);
create table if not exists staff_sessions (
 id bigint generated by default as identity primary key,
 staff_id bigint not null references staff(id) on delete cascade,
 token_hash text not null unique,
 created_at timestamptz not null default now(), expires_at timestamptz not null, user_agent text
);
create index if not exists idx_staff_sessions_staff on staff_sessions(staff_id);
create table if not exists queue_events (
 id bigint generated by default as identity primary key,
 queue_token_id bigint not null references queue_tokens(id) on delete cascade,
 staff_id bigint references staff(id) on delete set null,
 from_status text, to_status text not null, counter_id text, note text,
 created_at timestamptz not null default now()
);
alter table staff enable row level security;
alter table staff_credentials enable row level security;
alter table staff_sessions enable row level security;
alter table queue_events enable row level security;
create unique index if not exists uq_active_booking_slot on bookings(farmer_id,mandi_id,crop_id,booking_date,slot_start) where status <> 'CANCELLED';
